### ISSUE TITLE
部署并发性

### ISSUE THREAD

**Issue by zgd716** [WenmuZhou/DBNet.pytorch#111]
大佬，backbone：mobilenet   cpu部署的话，并发性有什么好的方案保证吗？

**Comment by WenmuZhou** [comment]
这个得看你选择的部署方案了，我这边没有做过测试

**Comment by zgd716** [comment]
> 这个得看你选择的部署方案了，我这边没有做过测试

大佬，backbone使用mobilenet ，导出onnx数据格式，有op不支持啊

**Comment by WenmuZhou** [comment]
啥op，我这边没有试过onnx
