### ISSUE TITLE
萌新请问：如果修改所用的backbone的话，都要改哪些文件呢？

### ISSUE THREAD

**Issue by Yui-Aragakki** [WenmuZhou/DBNet.pytorch#113]
你好，我现在想更改backbone由原来的resnet18到mbilenet，是只要修改一下tool中的train.py以及在config中新建一个使用mobilenet作为backbone的环境就可以了吗？

**Comment by xspring14** [comment]
大佬，这个库能将backbone改成用mobilenet么，望大佬能分享下经验
