### ISSUE TITLE
Segmentation body and Segmentation head

### ISSUE THREAD

**Issue by LanWong1** [WenmuZhou/DBNet.pytorch#12]
您好，十分感谢您的贡献，鄙人有一处不是很清楚。本项目是不是在论文模型的基础上还加了FPN，我感觉segmentation body的FPN层和 segmentation head 的DBHead是重复的。
您的代码显示，在backbone输出之后经过了FPN，还通过了DBHead，这两个似乎是一样的。

**Comment by WenmuZhou** [comment]
不一样的，本身论文的流程就是resnet+fpn+dbhead
