### ISSUE TITLE
遍历DataLoader时，得到的是个字典，请问值的来源在源码中的哪一处？

### ISSUE THREAD

**Issue by regainOWO** [WenmuZhou/DBNet.pytorch#129]
头都大了
`batch['img']`
`batch['shrink_map']`
`batch['threshold_map']`
这三个东西怎么来的啊啊啊啊啊

**Comment by WenmuZhou** [comment]
麻烦debug看看哈，具体是在这里
![image](https://user-images.githubusercontent.com/12406017/140040863-d543653a-0d4f-48c2-a953-9f25e129f912.png)
