### ISSUE TITLE
from models import get_model

### ISSUE THREAD

**Issue by xumoremore** [WenmuZhou/DBNet.pytorch#13]
(dlipy3) [alphamind@alphamind DBNet.pytorch-master]$ bash eval.sh
Traceback (most recent call last):
  File "tools/eval.py", line 72, in <module>
    eval = EVAL(args.model_path)
  File "tools/eval.py", line 18, in __init__
    from models import get_model
ModuleNotFoundError: No module named 'models'

![image](https://user-images.githubusercontent.com/48637105/74014850-79912c00-49ca-11ea-86ac-f9af9aadfc05.png)

**Comment by LanWong1** [comment]
> (dlipy3) [alphamind@alphamind DBNet.pytorch-master]$ bash eval.sh
> Traceback (most recent call last):
> File "tools/eval.py", line 72, in 
> eval = EVAL(args.model_path)
> File "tools/eval.py", line 18, in **init**
> from models import get_model
> ModuleNotFoundError: No module named 'models'
> 
> ![image](https://user-images.githubusercontent.com/48637105/74014850-79912c00-49ca-11ea-86ac-f9af9aadfc05.png)


<img width="1238" alt="image" src="https://user-images.githubusercontent.com/33218397/74095439-bf193a80-4b2b-11ea-951a-16155f27af03.png">

**Comment by xumoremore** [comment]
谢谢！

**Comment by xumoremore** [comment]
谢谢！
