### ISSUE TITLE
有推理时将预测的目标框裁剪下来保存的代码吗，后续需要送到CRNN识别

### ISSUE THREAD

**Issue by yufanxin** [WenmuZhou/DBNet.pytorch#131]

**Comment by liudatutu** [comment]
@yufanxin 在tools/predict.py中有输出bbox_list,用cv2中的最小外接矩形切割出来就行了

**Comment by wwp-max** [comment]
> @yufanxin 在tools/predict.py中有输出bbox_list,用cv2中的最小外接矩形切割出来就行了

请问能具体说一下吗，大四学生没有什么深度学习基础，希望大佬指教一下。

**Comment by wwp-max** [comment]
> _No description provided._

请问您解决了吗？
