### ISSUE TITLE
关于data_loader中deepcopy的疑问

### ISSUE THREAD

**Issue by SWHL** [WenmuZhou/DBNet.pytorch#155]
- 你好，感谢分享，一直有关注大佬
- 想向你请教一个问题，不太明白的是在`base_dataset.py`中的54行，为什么要用`copy.deepcopy()`来包一下`self.data_list[index]`？
https://github.com/WenmuZhou/DBNet.pytorch/blob/678b2ae55e018c6c16d5ac182558517a154a91ed/base/base_dataset.py#L52-L58

- 我在实验中发现，不加这一行，会有内存泄漏-_-，想不通为什么？

**Comment by WenmuZhou** [comment]
因为这里根据idx获取的内容是一个字典，后面做了字典内容的修改，不加dcp会有内存泄露的情况

**Comment by SWHL** [comment]
感谢，我再去研究一下
