### ISSUE TITLE
【小白求助】数据集在哪里找呀？

### ISSUE THREAD

**Issue by Roinnnn11** [WenmuZhou/DBNet.pytorch#191]
我找到的ICDAR数据集没有对应的json文件，已科学上网，但是没找到。这让我的data_loader函数无法运行（需要读取对应格式的json文件）。求大佬们指点

**Comment by WenmuZhou** [comment]
用我的OCRdataset库里的脚本转一下

**Comment by Roinnnn11** [comment]
好的！我看到了！谢谢
