### ISSUE TITLE
有预训练模型吗

### ISSUE THREAD

**Issue by beichen2012** [WenmuZhou/DBNet.pytorch#2]
请问是否方便给出预训练模型呢？

**Comment by WenmuZhou** [comment]
还没写完，等弄好了会放出来的

**Comment by beichen2012** [comment]
> 还没写完，等弄好了会放出来的

谢谢，期待ing...

**Comment by rm2886** [comment]
@WenmuZhou is it possible if we can use the pre-trained model from official DBNet for prediction or for transfer learning, if yes, please explain.

**Comment by WenmuZhou** [comment]
@rm2886  Yes, a simple way is to load all the parameters except the output convolutional layer, and then fine-tune it.
