### ISSUE TITLE
模型耗时较高

### ISSUE THREAD

**Issue by 562841850** [WenmuZhou/DBNet.pytorch#21]
在训练过程和测试中发现速度较慢，batch_size设置为32的时候，训练耗时像图中这样，测试时FPS是0.244。用的icdar2015_resnet18_FPN_DBhead_polyLR.yaml。请问这个耗时正常不？感觉好慢哪，麻烦WenmuZhou和各位大神帮忙看下，谢谢
![image](https://user-images.githubusercontent.com/60977646/79309164-75ced800-7f2c-11ea-87e5-5b4779e9f3ba.png)
![image](https://user-images.githubusercontent.com/60977646/79309228-87b07b00-7f2c-11ea-91e7-75f02a07eaa3.png)

**Comment by WenmuZhou** [comment]
你这个看着像cpu训练
