### ISSUE TITLE
why resize_text_polys=false on validation config

### ISSUE THREAD

**Issue by nai-kon** [WenmuZhou/DBNet.pytorch#23]
@WenmuZhou 
Thank you for sharing this great work.

I found `resize_text_polys : false` on `icdar2015_resnet18_FPN_DBhead_polyLR.yaml`.
`resize_text_polys ` is referenced at ResizeShortSize() for resizing validation image.
```python
scale = self.short_size / short_edge
im = cv2.resize(im, dsize=None, fx=scale, fy=scale)
if self.resize_text_polys:
    text_polys *= scale
``` 
When image is resized, text box positions also should be updated toward resize scale.
so I suppose `resize_text_polys` should be true.

Is there any reason that you set resize_text_polys=false?

**Comment by WenmuZhou** [comment]
Because the coordinates output by the post-processing method correspond to the original image

**Comment by nai-kon** [comment]
Thank you for your reply.
I didn't notice that.
Now, I found the program of scaling detection points to the original scale on SegDetectorRepresenter().

```python
box[:, 0] = np.clip(np.round(box[:, 0] / width * dest_width), 0, dest_width)
box[:, 1] = np.clip(np.round(box[:, 1] / height * dest_height), 0, dest_height)
```

So, resize_text_polys should be false, not true.
Close this issue.

**Comment by xiaozhubenben** [comment]
I think it is  wrong, text box positions should be scaled.
