### ISSUE TITLE
When I run the train.py on my dataset, the test model become very slow?

### ISSUE THREAD

**Issue by Williamwsk** [WenmuZhou/DBNet.pytorch#24]
![image](https://user-images.githubusercontent.com/38774781/80184598-7ad30c00-863d-11ea-9b6d-fd042b786f6b.png)

**Comment by WenmuZhou** [comment]
That ’s because the previous method of calculating iou is slow, I have recently updated it, you can try it, and the amount of text will also affect the speed

**Comment by hellmo718** [comment]
你这个更新的地方在哪里呢？我应该怎么试它
