### ISSUE TITLE
支持弯曲文本的训练和测试吗

### ISSUE THREAD

**Issue by shine-lcy** [WenmuZhou/DBNet.pytorch#25]
感谢文慕兄开源自己的复现。
目前版本支持弯曲文本的训练和测试吗？

**Comment by WenmuZhou** [comment]
训练和四点的没区别，测试将https://github.com/WenmuZhou/DBNet.pytorch/blob/master/predict.sh 里面的--polygon加上，然后把这里的代码放开https://github.com/WenmuZhou/DBNet.pytorch/blob/master/utils/ocr_metric/icdar2015/detection/iou.py#L150-L154，

下面的代码注释掉https://github.com/WenmuZhou/DBNet.pytorch/blob/master/utils/ocr_metric/icdar2015/detection/iou.py#L157-L161

**Comment by shine-lcy** [comment]
最近更新的open dataset是指什么呀..

**Comment by WenmuZhou** [comment]
是我的另一个项目  ocrdataset里面制作的数据集格式

**Comment by shine-lcy** [comment]
针对弯曲文本还是有点问题...
dataset.py中要把line40注释掉
`box = order_points_clockwise(np.array(list(map(float, params[:-1]))).reshape(-1, 2))`
order_points_clockwise会让框force到4点；
直接
`box = np.array(list(map(float, params[:-1]))).reshape(-1, 2)`

其次line41中的cv2.contourArea在我这边opencv4.1.2环境中对多个顶点的多边形输入会报错..
`error: (-215:Assertion failed) npoints >= 0 && (depth == CV_32F || depth == CV_32S) in function 'contourArea'`
我就直接注释掉计算面积了..

**Comment by whgao97** [comment]
老哥，为什么我改了还是有问题

**Comment by GanHey** [comment]
float改成int就行了
