### ISSUE TITLE
Ground truth format

### ISSUE THREAD

**Issue by xxxpsyduck** [WenmuZhou/DBNet.pytorch#27]
`x1, y1, x2, y2, x3, y3, x4, y4, annotation`

What is the "annotation"?

**Comment by WenmuZhou** [comment]
text in image

**Comment by xxxpsyduck** [comment]
@WenmuZhou But why do we need that? It is just a detection branch, isn't it?

**Comment by nai-kon** [comment]
For only a detection, I suppose the annotation label is unnecessary.
So you can fill it with meaningless word such as "foo" "bar".

**Comment by zcswdt** [comment]
> @WenmuZhou But why do we need that? It is just a detection branch, isn't it?

大佬，我也有同样的疑惑，这个不是文字检测吗？为啥还要真实的标签呢？标签不是在文字识别中才用得到吗？

**Comment by WenmuZhou** [comment]
因为需要这个来区分文字是否模糊，可以统一用`帅哥`来作为label

**Comment by zcswdt** [comment]
> 因为需要这个来区分文字是否模糊，可以统一用`帅哥`来作为label

谢谢大佬回复，但是我还是有点不明白，代码中我看到有ignore_tags，请问这个有什么作用吗？
![image](https://user-images.githubusercontent.com/43515926/88625050-a18c5d00-d0da-11ea-8e01-2cdaa1c6ccff.png)

**Comment by WenmuZhou** [comment]
这个就是标记哪些文字是模糊的，检测的时候不用训练

**Comment by zcswdt** [comment]
> 这个就是标记哪些文字是模糊的，检测的时候不用训练

好的，谢谢帮忙解疑。
