### ISSUE TITLE
训练时出现内存泄漏问题

### ISSUE THREAD

**Issue by xinyi61** [WenmuZhou/DBNet.pytorch#3]
感谢up主的无私开源。
我在训练时，发现存在内存泄漏的问题，不知道有没有好的手段定位这个问题？？？

**Comment by WenmuZhou** [comment]
已经解决掉了

**Comment by xinyi61** [comment]
什么时候会更新push上去？



来自 魅蓝 S6



-------- 原始邮件 --------
发件人：zhoujun <notifications@github.com>
时间：2019年12月13日 09:02
收件人："WenmuZhou/DBNet.pytorch" <DBNet.pytorch@noreply.github.com>
抄送：xinyi61 <xinyi61@hotmail.com>,Author <author@noreply.github.com>
主题：Re: [WenmuZhou/DBNet.pytorch] 训练时出现内存泄漏问题 (#3)


已经解决掉了

**Comment by WenmuZhou** [comment]
刚刚

**Comment by xinyi61** [comment]
为up主点赞👍👍👍



来自 魅蓝 S6



-------- 原始邮件 --------
发件人：zhoujun <notifications@github.com>
时间：2019年12月13日 09:09
收件人："WenmuZhou/DBNet.pytorch" <DBNet.pytorch@noreply.github.com>
抄送：xinyi61 <xinyi61@hotmail.com>,Author <author@noreply.github.com>
主题：Re: [WenmuZhou/DBNet.pytorch] 训练时出现内存泄漏问题 (#3)


刚刚
