### ISSUE TITLE
找不到get_model函数， 不是很清楚config yaml中的json文件具体内容

### ISSUE THREAD

**Issue by Highlightbeast** [WenmuZhou/DBNet.pytorch#34]
您好，尝试运行您的代码之后，我遇到了几个问题，实在不好意思打扰您，在这里提问。这是我在GitHub第一次提问，如果提问有冒犯到您的地方，我先说声不好意思。

1、请问这个get_model函数是被您删掉了吗？因为我翻了所有文件夹都没找到

![image](https://user-images.githubusercontent.com/49416769/83955620-f63af680-a854-11ea-9257-11559e76f586.png)
2、在训练这一步，根据您写的instruction， 我需要config the dataset['train']['dataset'['data_path']',dataset['validate']['dataset'['data_path']in config/icdar2015_resnet18_fpn_DBhead_polyLR.yaml

在您项目里面的config这个yaml文件里面的path，是一个json文件，不知道这个json文件的内容具体是什么呢？是test和train image的名字吗？还是image 名字和对应的？我看您dataset里面有test.txt和train.txt文件，而且文件内容就是./datasets/test/img/img_2.jpg	./datasets/test/gt/img_2.txt。 所以我有些疑惑，不知道您能不能截个json文件里面内容的图看看？实在是太感谢您了！
![image](https://user-images.githubusercontent.com/49416769/83955641-40bc7300-a855-11ea-9828-d92a915ac277.png)

**Comment by prfans** [comment]
First, the get_model in __init__.py is renamed to build_model.

**Comment by WenmuZhou** [comment]
json文件的定义在https://github.com/WenmuZhou/OCR_DataSet里有定义

**Comment by WenmuZhou** [comment]
@Highlightbeast 已经对eval.py 和predict.py文件做了修改

**Comment by Highlightbeast** [comment]
> @Highlightbeast 已经对eval.py 和predict.py文件做了修改

谢谢您啦

**Comment by Highlightbeast** [comment]
> First, the get_model in **init**.py is renamed to build_model.

Thanks :)

**Comment by Highlightbeast** [comment]
> json文件的定义在[https://github.com/WenmuZhou/OCR_DataSet里有定义](https://github.com/WenmuZhou/OCR_DataSet%E9%87%8C%E6%9C%89%E5%AE%9A%E4%B9%89)

啊真的太感谢您了，祝您周末愉快
