### ISSUE TITLE
训练几个epoch召回率和loss都变成0

### ISSUE THREAD

**Issue by VixeruntR** [WenmuZhou/DBNet.pytorch#37]
第一个epoch召回率0.5左右，然后一直变低，同时loss也在变低，大概四五个epoch之后突然全部变0，这可能是哪方面的原因呢？

**Comment by WenmuZhou** [comment]
100个epoch之后再看

**Comment by VixeruntR** [comment]
> 
> 
> 100个epoch之后再看

好的~

**Comment by VixeruntR** [comment]
> 
> 
> 100个epoch之后再看

方便的话，能否提供下您的预训练模型？

**Comment by WenmuZhou** [comment]
目前没有预训练

**Comment by VixeruntR** [comment]
> 
> 
> 目前没有预训练

好的，仍然感谢您！

**Comment by WenmuZhou** [comment]
那我先关了这个了

**Comment by kunyao2015** [comment]
@VixeruntR 您这边往后训练多个epoch后是正常的吗，我训练也是，第三轮开始recall就是0了，看着有点慌

**Comment by VixeruntR** [comment]
> 
> 
> @VixeruntR 您这边往后训练多个epoch后是正常的吗，我训练也是，第三轮开始recall就是0了，看着有点慌

我刚开始数据集大概2000张图像出现了这种情况，后来加了大概4000的icdar里面的数据，学习率设置的5e-4，batch_size=8，主干是resnet18，就没出现这个情况了，训练了20个epoch，recall 大概0.6，实际效果就已经非常好了。希望对你有帮助

**Comment by kunyao2015** [comment]
> > @VixeruntR 您这边往后训练多个epoch后是正常的吗，我训练也是，第三轮开始recall就是0了，看着有点慌
> 
> 我刚开始数据集大概2000张图像出现了这种情况，后来加了大概4000的icdar里面的数据，学习率设置的5e-4，batch_size=8，主干是resnet18，就没出现这个情况了，训练了20个epoch，recall 大概0.6，实际效果就已经非常好了。希望对你有帮助

感谢！我在resnet18下面训收敛比较快，换成resnet50就很慢了，100个epoch后也不见多好，效果还比上训练十几轮的resnet18

**Comment by VixeruntR** [comment]
我也是。。训练20轮的resnet18是最香的。。

**Comment by VixeruntR** [comment]
> 
> 
> > > @VixeruntR 您这边往后训练多个epoch后是正常的吗，我训练也是，第三轮开始recall就是0了，看着有点慌
> > 
> > 
> > 我刚开始数据集大概2000张图像出现了这种情况，后来加了大概4000的icdar里面的数据，学习率设置的5e-4，batch_size=8，主干是resnet18，就没出现这个情况了，训练了20个epoch，recall 大概0.6，实际效果就已经非常好了。希望对你有帮助
> 
> 感谢！我在resnet18下面训收敛比较快，换成resnet50就很慢了，100个epoch后也不见多好，效果还比上训练十几轮的resnet18

我也是。。训练20轮的resnet18是最香的。。

**Comment by xxllp** [comment]
训练几百张数据是不是容易过拟合啊

**Comment by VixeruntR** [comment]
> 
> 
> 训练几百张数据是不是容易过拟合啊

几百张有点太少了。。

**Comment by 619268640** [comment]
@VixeruntR 你好，请问，我用了几百张图片训练，1200轮都跑完了，P，R，F仍然是0，是什么原因呢？几百张可能效果不好，不不至于全都是0啊

**Comment by remeberWei** [comment]
> @VixeruntR 你好，请问，我用了几百张图片训练，1200轮都跑完了，P，R，F仍然是0，是什么原因呢？几百张可能效果不好，不不至于全都是0啊

有可能就是你的pyrorch版本跟cuda版本不匹配
