### ISSUE TITLE
关于open_dataset

### ISSUE THREAD

**Issue by xiaozhubenben** [WenmuZhou/DBNet.pytorch#38]
想问下open_dataset的格式 中，标注的polygon是否支持大于4个点，谢谢。
icdar2019 lsvt数据集中有些标注大于4个点的，我想转为open_dataset训练试试，不知道能不能用？

**Comment by WenmuZhou** [comment]
支持

**Comment by xiaozhubenben** [comment]
谢谢/

**Comment by zcswdt** [comment]
> 集中有些标注大于4个点的，我想转为open_dataset训练试

您好请问一下，icdar2019_lsvt这个数据集的全标注的标签是josn格式的，您那边是怎么处理的呢。我也想用这个数据训练。谢谢！

**Comment by WenmuZhou** [comment]
参考我的ocrdataset仓库
