### ISSUE TITLE
unnecessary value `1e-8` on calculating f1 score

### ISSUE THREAD

**Issue by nai-kon** [WenmuZhou/DBNet.pytorch#39]
There is an unnecessary value `1e-8` to avoid zero division.

 `utils/ocr_metric/icdar2015/quad_metric.py`
```python
fmeasure_score = 2 * precision.val * recall.val / (precision.val + recall.val + 1e-8)
```

Yes, 1e-8 is very small value, but it might effect to the f1 score.
I recommend to calculate like below.

```python
f1 = 0 if (p + r) == 0 else 2 * p * r / (p + r)
```

**Comment by WenmuZhou** [comment]
I will test this
