### ISSUE TITLE
想問一下pred與result的差異

### ISSUE THREAD

**Issue by kaieason** [WenmuZhou/DBNet.pytorch#41]
![pred圖](https://i.ibb.co/hYkqxYX/test01-pred.jpg)

![result圖](https://i.ibb.co/XkLmmQQ/test01-result.jpg)

從result的結果可以看到，有部分的字沒有被框到

想請問應該要怎麼調整，謝謝

**Comment by WenmuZhou** [comment]
predict.sh里的box_thresh调低

**Comment by kunyao2015** [comment]
这个问题解决了吗，我也有类似现象，调低了box_thresh，并没有改善 @kaieason @WenmuZhou

**Comment by vincezengqiang** [comment]
我的也是  训练log的acc、iou都已经很高了，但是测试时漏检很严重

**Comment by vincezengqiang** [comment]
请问你们解决了吗

**Comment by congjianting** [comment]
我这也发现存在漏检多个不理解的目标现象, 调整box_thresh并不能改善问题.

**Comment by futureisatyourhand** [comment]
> 我这也发现存在漏检多个不理解的目标现象, 调整box_thresh并不能改善问题.
请问，最后解决了嘛，感谢
