### ISSUE TITLE
报错 KeyError: 'type'

### ISSUE THREAD

**Issue by ganggang233** [WenmuZhou/DBNet.pytorch#42]
您好 我这里报错 KeyError: 'type'，具体如下：
Traceback (most recent call last):
  File "tools/predict.py", line 140, in <module>
    model = Pytorch_model(args.model_path, post_p_thre=args.thre, gpu_id=0)
  File "tools/predict.py", line 55, in __init__
    self.model = build_model(config['arch'].pop('type'), **config['arch'])
KeyError: 'type'

请问可以解决吗？谢谢！

**Comment by WenmuZhou** [comment]
帖一下config

**Comment by ganggang233** [comment]
> 帖一下config

name: DBNet
base: ['config/icdar2015.yaml']
arch:
  type: Model
  backbone:
    type: deformable_resnet18
    pretrained: true
  neck:
    type: FPN
    inner_channels: 256
  head:
    type: DBHead
    out_channels: 2
    k: 50
post_processing:
  type: SegDetectorRepresenter
  args:
    thresh: 0.3
    box_thresh: 0.7
    max_candidates: 1000
    unclip_ratio: 1.5 # from paper
metric:
  type: QuadMetric
  args:
    is_output_polygon: false
loss:
  type: DBLoss
  alpha: 1
  beta: 10
  ohem_ratio: 3
optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    amsgrad: true
lr_scheduler:
  type: WarmupPolyLR
  args:
    warmup_epoch: 3
trainer:
  seed: 2
  epochs: 500
  log_iter: 10
  show_images_iter: 50
  resume_checkpoint: ''
  finetune_checkpoint: ''
  output_dir: output
  tensorboard: true
dataset:
  train:
    dataset:
      args:
        data_path:
          - /home/gang/PycharmProject/DBNet.pytorch/datasets/train.txt
        img_mode: RGB
    loader:
      batch_size: 8
      shuffle: true
      pin_memory: true
      num_workers: 4
      collate_fn: ''
  validate:
    dataset:
      args:
        data_path:
          - /home/gang/PycharmProject/DBNet.pytorch/datasets/test.txt
        pre_processes:
          - type: ResizeShortSize
            args:
              short_size: 736
              resize_text_polys: false
        img_mode: RGB
    loader:
      batch_size: 1
      shuffle: true
      pin_memory: false
      num_workers: 4
      collate_fn: ICDARCollectFN

**Comment by ganggang233** [comment]
> name: DBNet
base: ['config/icdar2015.yaml']
arch:
  type: Model
  backbone:
    type: deformable_resnet18
    pretrained: true
  neck:
    type: FPN
    inner_channels: 256
  head:
    type: DBHead
    out_channels: 2
    k: 50
post_processing:
  type: SegDetectorRepresenter
  args:
    thresh: 0.3
    box_thresh: 0.7
    max_candidates: 1000
    unclip_ratio: 1.5 # from paper
metric:
  type: QuadMetric
  args:
    is_output_polygon: false
loss:
  type: DBLoss
  alpha: 1
  beta: 10
  ohem_ratio: 3
optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    amsgrad: true
lr_scheduler:
  type: WarmupPolyLR
  args:
    warmup_epoch: 3
trainer:
  seed: 2
  epochs: 500
  log_iter: 10
  show_images_iter: 50
  resume_checkpoint: ''
  finetune_checkpoint: ''
  output_dir: output
  tensorboard: true
dataset:
  train:
    dataset:
      args:
        data_path:
          - /home/gang/PycharmProject/DBNet.pytorch/datasets/train.txt
        img_mode: RGB
    loader:
      batch_size: 8
      shuffle: true
      pin_memory: true
      num_workers: 4
      collate_fn: ''
  validate:
    dataset:
      args:
        data_path:
          - /home/gang/PycharmProject/DBNet.pytorch/datasets/test.txt
        pre_processes:
          - type: ResizeShortSize
            args:
              short_size: 736
              resize_text_polys: false
        img_mode: RGB
    loader:
      batch_size: 1
      shuffle: true
      pin_memory: false
      num_workers: 4
      collate_fn: ICDARCollectFN

**Comment by ganggang233** [comment]
[icdar2015_dcn_resnet18_FPN_DBhead_polyLR.zip](https://github.com/WenmuZhou/DBNet.pytorch/files/4802019/icdar2015_dcn_resnet18_FPN_DBhead_polyLR.zip)

**Comment by WenmuZhou** [comment]
下载不了，那你直接贴内容吧

**Comment by ganggang233** [comment]
> 下载不了，那你直接贴内容吧

name: DBNet
base: ['config/icdar2015.yaml']
arch:
  type: Model
  backbone:
    type: deformable_resnet18
    pretrained: true
  neck:
    type: FPN
    inner_channels: 256
  head:
    type: DBHead
    out_channels: 2
    k: 50
post_processing:
  type: SegDetectorRepresenter
  args:
    thresh: 0.3
    box_thresh: 0.7
    max_candidates: 1000
    unclip_ratio: 1.5 # from paper
metric:
  type: QuadMetric
  args:
    is_output_polygon: false
loss:
  type: DBLoss
  alpha: 1
  beta: 10
  ohem_ratio: 3
optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    amsgrad: true
lr_scheduler:
  type: WarmupPolyLR
  args:
    warmup_epoch: 3
trainer:
  seed: 2
  epochs: 500
  log_iter: 10
  show_images_iter: 50
  resume_checkpoint: ''
  finetune_checkpoint: ''
  output_dir: output
  tensorboard: true
dataset:
  train:
    dataset:
      args:
        data_path:
          - /home/gang/PycharmProject/DBNet.pytorch/datasets/train.txt
        img_mode: RGB
    loader:
      batch_size: 8
      shuffle: true
      pin_memory: true
      num_workers: 4
      collate_fn: ''
  validate:
    dataset:
      args:
        data_path:
          - /home/gang/PycharmProject/DBNet.pytorch/datasets/test.txt
        pre_processes:
          - type: ResizeShortSize
            args:
              short_size: 736
              resize_text_polys: false
        img_mode: RGB
    loader:
      batch_size: 1
      shuffle: true
      pin_memory: false
      num_workers: 4
      collate_fn: ICDARCollectFN

**Comment by WenmuZhou** [comment]
我估计是你保存的model里的config里没有type，手动指定一下吧

**Comment by ganggang233** [comment]
好的我试一下 多谢

**Comment by dcdethan** [comment]
你好，我遇到了同样的问题，请问您解决了吗

**Comment by wayneszq** [comment]
> 你好，我遇到了同样的问题，请问您解决了吗

如果是dataset报错KeyError: 'type', 可能是因为yaml里缺失了[dataset][type]这个字段。需要手工添加，train和val都需要加。我在复现IC15数据集时候发现的这个问题，改了一下，就正常了。
```
dataset:
  train:
    dataset:
      type:
        ICDAR2015Dataset # 这里需要添加
      args:
        data_path:
          - /YOUR/OWN/PATH/train.txt
        img_mode: RGB
```

**Comment by dcdethan** [comment]
> > 你好，我遇到了同样的问题，请问您解决了吗
> 
> 如果是dataset报错KeyError: 'type', 可能是因为yaml里缺失了[dataset][type]这个字段。需要手工添加，train和val都需要加。我在复现IC15数据集时候发现的这个问题，改了一下，就正常了。
> 
> ```
> dataset:
>   train:
>     dataset:
>       type:
>         ICDAR2015Dataset # 这里需要添加
>       args:
>         data_path:
>           - /YOUR/OWN/PATH/train.txt
>         img_mode: RGB
> ```

好的，感谢您的回复。
