### ISSUE TITLE
TypeError: build_model() got an unexpected keyword argument 'backbone'

### ISSUE THREAD

**Issue by shen865069799** [WenmuZhou/DBNet.pytorch#45]
hi, when run predict.sh,this error occur,how can i solve it,thanks

**Comment by shen865069799** [comment]
i'd solved it, build_model's param should equal to train phase

**Comment by dcdethan** [comment]
hi,I have met the same problem , would you like to tell me how to solve it?what's the mean "build_model's param should equal to train phase".thank,you

**Comment by shen865069799** [comment]
> hi,I have met the same problem , would you like to tell me how to solve it?what's the mean "build_model's param should equal to train phase".thank,you

you can check when you train your model, what's param is passed in the build_model,and in predict.py param of build_model should same with it; i modified it with below pic,and it works:
![image](https://user-images.githubusercontent.com/31476124/86890531-0550e500-c130-11ea-9f63-1133c058a54a.png)

**Comment by dcdethan** [comment]
thank you for your replying.I solve it by your suggestion.thanks a lot.

**Comment by WenmuZhou** [comment]
this have been fixed in latest commit
