### ISSUE TITLE
In some case, long white zone in pred.jpg is no be detected as text zone with polygons in output image.

### ISSUE THREAD

**Issue by wolfryu** [WenmuZhou/DBNet.pytorch#46]
Thank you for your sharing!
In some case, I can see white zone in pred.jpg but no polygons in the same place. why that happens?
for example:
![image](https://user-images.githubusercontent.com/63227212/86456819-9f461580-bd5d-11ea-91ae-40bd2983d19c.png)
the short white zone is detected as text zone with polygons in output image. but the long white zone is not detected as text zone with polygons.

I tried to set a very low --thre, but not working, output the same thing.
Is there any place checked the length of white zone?

**Comment by WenmuZhou** [comment]
Is the long white zone in segmentation in this line？https://github.com/WenmuZhou/DBNet.pytorch/blob/master/post_processing/seg_detector_representer.py#L30

**Comment by wolfryu** [comment]
@WenmuZhou yes, this is the image of segmentation (of another image):
![image](https://user-images.githubusercontent.com/63227212/86551749-f8da5a00-bf80-11ea-986b-a21f968f981a.png)
the long white zone is not detected as text zone.

**Comment by wolfryu** [comment]
I just find that polygons is abnormal but box works fine, detect white zone as text zone. Maybe there is a bug in self.polygons_from_bitmap .
