### ISSUE TITLE
about train

### ISSUE THREAD

**Issue by zcswdt** [WenmuZhou/DBNet.pytorch#5]
I downloaded your code and modified the training path, but it will report an error when training with a single GPU.
`Traceback (most recent call last):
  File "tools/train.py", line 67, in <module>
    from utils import parse_config
ModuleNotFoundError: No module named 'utils'`

**Comment by WenmuZhou** [comment]
I not meet that error

**Comment by zcswdt** [comment]
I reposition it, thank you for your reply
