### ISSUE TITLE
FPN结构是不是有问题

### ISSUE THREAD

**Issue by dedety2** [WenmuZhou/DBNet.pytorch#52]
https://github.com/WenmuZhou/DBNet.pytorch/blob/678b2ae55e018c6c16d5ac182558517a154a91ed/models/neck/FPN.py#L39
在这里c2, c3, c4, c5 都使用了同一个特征层的输出，与原始FPN结构不一致。

**Comment by WenmuZhou** [comment]
没啥问题的
