### ISSUE TITLE
这个实现和官方代码有啥区别呢?

### ISSUE THREAD

**Issue by allenxcp** [WenmuZhou/DBNet.pytorch#54]
WenmuZhou: 
   非常感谢作者开源,请问这个工程和DBnet源工程(https://github.com/MhLiao/DB)有啥区别啊?改进了啥

谢谢

**Comment by WenmuZhou** [comment]
最大的特点是人性化，支持更多backbone

**Comment by zcswdt** [comment]
> 最大的特点是人性化，支持更多backbone

人性化这个我是非常支持的，我配置好了官方的仓库，跑通了训练，去读代码的时候，真是晦涩难懂啊，我今天来尝试一下大佬的代码。
