### ISSUE TITLE
A question about polygons

### ISSUE THREAD

**Issue by dy1998** [WenmuZhou/DBNet.pytorch#55]
Hello , I want to use polygons during training. However, after delete 'text_polys' in filter_keys, some error occur at dataloader, what should I do?

ValueError: some of the strides of a given numpy array are negative. This is currently not supported, but will be added in future releases.

**Comment by dy1998** [comment]
It is a problem about my dataloader, never mind.

**Comment by Smart-tan** [comment]
你好  你是怎样在训练期间使用多边形  或者是怎样训练Totaltext不规则的
