### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by courao** [WenmuZhou/DBNet.pytorch#6]
你好，对老哥代码风格比较喜欢所以基本上几个仓库都star了，有一个问题想问问你，
因为我看到老哥几个仓库都基本只给了icdar15数据结果，代码里dataset也只有icdar15和synthText，所以想了解一下你有对其他数据集比如一些弯曲文本的数据集做过实验吗？

**Comment by WenmuZhou** [comment]
没有呢，没有时间做
