### ISSUE TITLE
如何把训练好的模型转换为onnx 老是有不支持的操作

### ISSUE THREAD

**Issue by huihuixiaohuihui** [WenmuZhou/DBNet.pytorch#65]

**Comment by toxic-0518** [comment]
把model - head 里面的 DBHead.py 中的upsample的mode换成"nearest"即可

**Comment by zcswdt** [comment]
> _No description provided._

请问你转成功了吗？想学习一下。

**Comment by huihuixiaohuihui** [comment]
成功了 你想我提供你什么?

**Comment by huihuixiaohuihui** [comment]
> > _No description provided._
> 
> 请问你转成功了吗？想学习一下。

成功了  你想我提供你什么？

**Comment by zcswdt** [comment]
> > > _No description provided._
> > 
> > 
> > 请问你转成功了吗？想学习一下。
> 
> 成功了 你想我提供你什么？

可以加一下你qq或者微信吗？想向你请教一下，如何转换。

**Comment by huihuixiaohuihui** [comment]
> > > > _No description provided._
> > > 
> > > 
> > > 请问你转成功了吗？想学习一下。
> > 
> > 
> > 成功了 你想我提供你什么？
> 
> 可以加一下你qq或者微信吗？想向你请教一下，如何转换。

WECHAT  2518956478

**Comment by SWHL** [comment]
参考这个：#98 (comment)
可以成功转换
