### ISSUE TITLE
SynthText训练崩溃

### ISSUE THREAD

**Issue by toxic-0518** [WenmuZhou/DBNet.pytorch#71]
用SynthText训练模型(Docker)崩溃
现象是dataloader等待超时被kill, 设置num_workers=0仍会出现这种情况，且多次复现。无论在dokcer启动时指定--ipc=host还是强制设定shm都无法解决问题，且后台没有log信息。关注cpu/gpu/内存使用情况后并未发现占用非常多的资源或者占用资源突变的情况。
怀疑opencv读了有问题的图片，在imread的地方加try catch发现并未捕获异常，应该不是这里的问题。
另外SynthText的data loader好像有几个小bug, 1. 初始化参数少了个ignore_tags导致会把transformer传给ignore_tags导致dataset初始化失败， 以及 2. 数据集路径读取进来是一个char list (['S', 'y', 'n', 't', 'h', ....]), 需要"".join(data_path)转成str才能正常初始化dataset。

**Comment by yangtianyu92** [comment]
我第一次训练的时候没有碰到你说的问题，安稳训练了三天。重新训练后我也碰到你说的问题了。~~~目测是内存泄漏，得一点点查过去了。我是batch32 step749 必定内存泄漏。

**Comment by toxic-0518** [comment]
> 我第一次训练的时候没有碰到你说的问题，安稳训练了三天。重新训练后我也碰到你说的问题了。~~~目测是内存泄漏，得一点点查过去了。我是batch32 step749 必定内存泄漏。

怀疑是SynthText数据集太大了导致的
用icdar+cocotext就没出现过
作者在读图片的时候已经做过异常处理了，所以应该不是图片错误导致的。
我觉得这个可能是pytorch dataloader的问题。

**Comment by yangtianyu92** [comment]
我也高度怀疑是pytorch dataloader的问题，所以我把base_dataset.py里面cv2读取图片的方式换成PIL读取方式了，结果发现更垮了哈哈哈，这次连内存泄露都没有，直接core dump安排上。这次我把数据增强这段给去掉看看。

**Comment by hualitlc** [comment]
@yangtianyu92 @toxic-0518 请问你们测试SynthText数据集的时候，是用的SynthText_resnet18_FPN_DBhead_polyLR.yaml这个配置文件吗？里面的dataset的路径怎么写的？我写到/data/XXX/data/SynthText/，一直报错。谢谢！
`Traceback (most recent call last):
  File "tools/train.py", line 78, in <module>
    main(config)
  File "tools/train.py", line 37, in main
    train_loader = get_dataloader(config['dataset']['train'], config['distributed'])
  File "/data/tianlc/code/DBNet.pytorch/data_loader/__init__.py", line 84, in get_dataloader
    _dataset = get_dataset(data_path=data_path, module_name=dataset_name, transform=img_transfroms, dataset_args=dataset_args)
  File "/data/tianlc/code/DBNet.pytorch/data_loader/__init__.py", line 24, in get_dataset
    **dataset_args)
  File "/data/tianlc/code/DBNet.pytorch/data_loader/dataset.py", line 102, in __init__
    self.dataRoot = pathlib.Path(data_path)
  File "/data/tianlc/conda/envs/dbnet/lib/python3.6/pathlib.py", line 1001, in __new__
    self = cls._from_parts(args, init=False)
  File "/data/tianlc/conda/envs/dbnet/lib/python3.6/pathlib.py", line 656, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/data/tianlc/conda/envs/dbnet/lib/python3.6/pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not list
`

**Comment by toxic-0518** [comment]
> 我也高度怀疑是pytorch dataloader的问题，所以我把base_dataset.py里面cv2读取图片的方式换成PIL读取方式了，结果发现更垮了哈哈哈，这次连内存泄露都没有，直接core dump安排上。这次我把数据增强这段给去掉看看。

我也换成PIL了 还是崩。。囧。。

**Comment by toxic-0518** [comment]
> @yangtianyu92 @toxic-0518 请问你们测试SynthText数据集的时候，是用的SynthText_resnet18_FPN_DBhead_polyLR.yaml这个配置文件吗？里面的dataset的路径怎么写的？我写到/data/XXX/data/SynthText/，一直报错。谢谢！
> `Traceback (most recent call last): File "tools/train.py", line 78, in <module> main(config) File "tools/train.py", line 37, in main train_loader = get_dataloader(config['dataset']['train'], config['distributed']) File "/data/tianlc/code/DBNet.pytorch/data_loader/__init__.py", line 84, in get_dataloader _dataset = get_dataset(data_path=data_path, module_name=dataset_name, transform=img_transfroms, dataset_args=dataset_args) File "/data/tianlc/code/DBNet.pytorch/data_loader/__init__.py", line 24, in get_dataset **dataset_args) File "/data/tianlc/code/DBNet.pytorch/data_loader/dataset.py", line 102, in __init__ self.dataRoot = pathlib.Path(data_path) File "/data/tianlc/conda/envs/dbnet/lib/python3.6/pathlib.py", line 1001, in __new__ self = cls._from_parts(args, init=False) File "/data/tianlc/conda/envs/dbnet/lib/python3.6/pathlib.py", line 656, in _from_parts drv, root, parts = self._parse_args(args) File "/data/tianlc/conda/envs/dbnet/lib/python3.6/pathlib.py", line 640, in _parse_args a = os.fspath(a) TypeError: expected str, bytes or os.PathLike object, not list `

这个就是我之前说的问题，这个path由于代码逻辑的bug,得到的path是一个list而不是一个string。你把这个data path打印出来就知道问题在哪了。
解决方法就是将这个list拼成一个string

**Comment by yangtianyu92** [comment]
不太清楚你具体情况，我说下我的做法。
你看下config文件夹下的icdar2015_dcn_resnet18_FPN_DBhead_polyLR.yaml 
dataset:
  train:
    dataset:
      args:
        data_path:
          - ./datasets/train.txt

这个地址是这么写的，跟config里面的是不一致的。
其次data_loader文件夹下的dataset.py 的SynthTextDataset类型初始化要这么改一下。这样就能跑了。
![33](https://user-images.githubusercontent.com/30435412/92580438-ef42da80-f2c0-11ea-96d6-11dc042a70bd.png)

**Comment by yangtianyu92** [comment]
> > 我也高度怀疑是pytorch dataloader的问题，所以我把base_dataset.py里面cv2读取图片的方式换成PIL读取方式了，结果发现更垮了哈哈哈，这次连内存泄露都没有，直接core dump安排上。这次我把数据增强这段给去掉看看。
> 
> 我也换成PIL了 还是崩。。囧。。

哈哈哈哈哈，我在想要不要一次少载入一点，然后脚本分开反复Train。动不动内存占用飙到300多个G，太顶了。

**Comment by hualitlc** [comment]
> 不太清楚你具体情况，我说下我的做法。
> 你看下config文件夹下的icdar2015_dcn_resnet18_FPN_DBhead_polyLR.yaml
> dataset:
> train:
> dataset:
> args:
> data_path:
> - ./datasets/train.txt
> 
> 这个地址是这么写的，跟config里面的是不一致的。
> 其次data_loader文件夹下的dataset.py 的SynthTextDataset类型初始化要这么改一下。这样就能跑了。
> ![33](https://user-images.githubusercontent.com/30435412/92580438-ef42da80-f2c0-11ea-96d6-11dc042a70bd.png)

那你不是用的SynthText_resnet18_FPN_DBhead_polyLR.yaml这个配置文件么？

**Comment by yangtianyu92** [comment]
对的，这俩config的datapath写法不一样，跟着写就上当了。




在2020年09月09日 17:35，David Tian 写道：

不太清楚你具体情况，我说下我的做法。
你看下config文件夹下的icdar2015_dcn_resnet18_FPN_DBhead_polyLR.yaml
dataset:
train:
dataset:
args:
data_path:

./datasets/train.txt

这个地址是这么写的，跟config里面的是不一致的。
其次data_loader文件夹下的dataset.py 的SynthTextDataset类型初始化要这么改一下。这样就能跑了。


那你不是用的SynthText_resnet18_FPN_DBhead_polyLR.yaml这个配置文件么？

**Comment by toxic-0518** [comment]
It seems that this is a pytorch dataloader bug. 
I' ll close this ticket.
