### ISSUE TITLE
这个repo与原作者的区别在哪里呢？

### ISSUE THREAD

**Issue by bxhandhxb** [WenmuZhou/DBNet.pytorch#84]
请问这个repo与原作者的区别在哪里呢？  不管是在数据处理/后处理/模型结构上的区别都可以，大佬有具体的介绍吗？

**Comment by thcheung** [comment]
same question here.

**Comment by WenmuZhou** [comment]
代码风格更好，支持配置式管理，支持更多backbone，支持tensorboard
