### ISSUE TITLE
anyconfig.globals.UnknownFileTypeError: No parser found for file 'file extension=yaml'

### ISSUE THREAD

**Issue by zzcqinag** [WenmuZhou/DBNet.pytorch#85]
when l run sh multi_gpu_train.sh,l get the error:
anyconfig.globals.UnknownFileTypeError: No parser found for file 'file extension=yaml'

**Comment by WenmuZhou** [comment]
pip install pyyaml

**Comment by zzcqinag** [comment]
thank you！



---Original---

**Comment by sharonjunjun** [comment]
can you succesed multi gpu training, i failed
