### ISSUE TITLE
Predicting multiple images, and output the predicted labels

### ISSUE THREAD

**Issue by ghost** [WenmuZhou/DBNet.pytorch#9]
@WenmuZhou 
Thank you for your hard work,
It would be great to have options to:

- Predict all the images in a directory.
- Option to output the predicted `.txt` labels for each image.
- Option to choose to predict as `box rectangle` or `polygon`.
- Option to set `box_thresh`

**Comment by WenmuZhou** [comment]
1. you can modify the predict.py to support this or use eval.py
2. same to 1
3. seed `is_output_polygon=True` in this [line](https://github.com/WenmuZhou/DBNet.pytorch/blob/master/tools/predict.py#L77) can output polygon
4. https://github.com/WenmuZhou/DBNet.pytorch/blob/master/config/icdar2015_dcn_resnet18_FPN_DBhead_polyLR.yaml#L21

**Comment by ghost** [comment]
1+2 It is great having an option `--input_dir` also `--output_dir`
3. Changed `predict.py ` to ```box_list, score_list = self.post_process(batch, preds, is_output_polygon=True)```, now getting error:
```
  File "tools/predict.py", line 101, in <module>
    preds, boxes_list, t = model.predict(img_path)
  File "tools/predict.py", line 77, in predict
    box_list, score_list = self.post_process(batch, preds, is_output_polygon=True)
  File "/home/home/p10/DBNet.pytorch/post_processing/seg_detector_representer.py", line 36, in __call__
    boxes, scores = self.polygons_from_bitmap(pred[batch_index], segmentation[batch_index], width, height)
  File "/home/home/p10/DBNet.pytorch/post_processing/seg_detector_representer.py", line 70, in polygons_from_bitmap
    score = self.box_score_fast(pred, contour)
  File "/home/home/p10/DBNet.pytorch/post_processing/seg_detector_representer.py", line 169, in box_score_fast
    ymin = np.clip(np.floor(box[:, 1].min()).astype(np.int), 0, h - 1)
IndexError: index 1 is out of bounds for axis 1 with size 1
```
4. Thanks

**Comment by WenmuZhou** [comment]
is a bug, has fixed

**Comment by ghost** [comment]
1. Still it would be great having the option to predict all the images in a directory. Perhaps `--input_dir` also `--output_dir`
2. When running `bash predict.sh` I am getting error, this error appears only when using `--polygon`:
```
(dbnet) home@home-desktop:~/p12/DBNet.pytorch$ bash predict.sh 
Namespace(img_path='./input/img_1.jpg', model_path='./output/DBNet_resnet18_FPN_DBHead/checkpoint/model_best.pth', polygon=True, save_resut=True, show=True)
device: cuda:0
/home/home/anaconda3/envs/dbnet/lib/python3.7/site-packages/torch/nn/functional.py:2548: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode))
Traceback (most recent call last):
  File "tools/predict.py", line 126, in <module>
    preds, boxes_list, score_list, t = model.predict(args.img_path, is_output_polygon=args.polygon)
  File "tools/predict.py", line 93, in predict
    idx = [x.sum() > 0 for x in box_list]
  File "tools/predict.py", line 93, in <listcomp>
    idx = [x.sum() > 0 for x in box_list]
AttributeError: 'list' object has no attribute 'sum'
```

**Comment by WenmuZhou** [comment]
2. this line https://github.com/WenmuZhou/DBNet.pytorch/blob/master/post_processing/seg_detector_representer.py#L91

**Comment by ghost** [comment]
hmmm...
so now how to solve this issue?

**Comment by WenmuZhou** [comment]
can you privide a test model and test img

**Comment by ghost** [comment]
[Here you go](https://drive.google.com/drive/folders/1oka91O4KRv0rr7Cnul7QUuif8Tc-QN50?usp=sharing)

- Also, did you have a look at predicting all the images in a folder

**Comment by WenmuZhou** [comment]
now, the bug is fixed and input_folder args is add to predict.sh

**Comment by ghost** [comment]
Thanks man,
At this point, your repository have exceeded beyond the official DB repo.
Keep it up!
