### ISSUE TITLE
mnn输出不对

### ISSUE THREAD

**Issue by cendelian** [WenmuZhou/DBNet.pytorch#99]
大佬你好，我是用mobilenetv3作为backbone训练模型，并成功转onnx和进行onnx推理。

然后我将onnx模型转mnn，发现mnn模型输出形状是对的，但1数值完全不正确。但后后面mnn推理不对。

请问这个有可能是什么原因造成吗

**Comment by cendelian** [comment]
> 大佬你好，我是用mobilenetv3作为backbone训练模型，并成功转onnx和进行onnx推理。
> 
> 然后我将onnx模型转mnn，发现mnn模型输出形状是对的，但1数值完全不正确。但后后面mnn推理不对。
> 
> 请问这个有可能是什么原因造成吗

已解决，将mnn输出格式转为nchw即可

**Comment by ML-Mr-J** [comment]
您好，可变卷积可以转onnx么？
